from .client import (
    ClientConfig,
    LecturersEndpoints,
    RuzClient,
)
from .errors import RuzAuthError, RuzClientError, RuzHttpError
from .http.endpoints import (
    UNSET,
    GroupCreate,
    GroupRead,
    GroupSearchHit,
    GroupsEndpoints,
    GroupUpdate,
    Lecturer,
    RuzGroupSearchItem,
    ScheduleEndpoints,
    SearchEndpoints,
    UserCreate,
    UserRead,
    UserScheduleLesson,
    UsersEndpoints,
    UserUpdate,
)

__all__ = [
    "ClientConfig",
    "RuzClient",
    "Lecturer",
    "RuzClientError",
    "RuzAuthError",
    "RuzHttpError",
    "GroupCreate",
    "GroupRead",
    "GroupSearchHit",
    "GroupUpdate",
    "GroupsEndpoints",
    "RuzGroupSearchItem",
    "ScheduleEndpoints",
    "SearchEndpoints",
    "UNSET",
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "UserScheduleLesson",
    "UsersEndpoints",
    "LecturersEndpoints",
]
